
networks:
    webapp:
        driver: bridge


services:
    nginx:
        image: nginx:stable-alpine
        container_name: ${APP_NAME}_nginx
        ports:
            - "8000:80"
        links:
            - php
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf:rw
            - ./docker/logs/nginx:/var/logs/nginx:rw
        depends_on:
            - php
            - db
        networks:
            - webapp

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: ${APP_NAME}_php
        volumes:
            - ./:/var/www/html
        ports:
            - "9001:9000"
        networks:
            - webapp

    db:
        image: mysql:latest
        restart: unless-stopped
        container_name: mysql_db
        ports:
            - '3306:3306'
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
        environment:
            MYSQL_USER: test
            MYSQL_DATABASE: ${DB_USERNAME}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - webapp


    phpmyadmin:
        image: phpmyadmin/phpmyadmin:5
        container_name: ${APP_NAME}_phpmyadmin
        ports:
            - 8888:80
        depends_on:
            - db
        networks:
            - webapp

    node:
        image: node:18
        container_name: ${APP_NAME}_node
        ports:
        - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        volumes:
        - ./:/var/www/html
        working_dir: /var/www/html
        command: [
            "yarn", "run", "dev",
            "--port", "${VITE_PORT:-5173}",
            "--host", "0.0.0.0"
        ]
        networks:
            - webapp

    soketi:
        container_name: soketi
        image: 'quay.io/soketi/soketi:latest-16-alpine'
        environment:
            SOKETI_DEBUG: '${SOKETI_DEBUG:-1}'
            SOKETI_METRICS_SERVER_PORT: '9601'
            SOKETI_DEFAULT_APP_ID: '${PUSHER_APP_ID}'
            SOKETI_DEFAULT_APP_KEY: '${PUSHER_APP_KEY}'
            SOKETI_DEFAULT_APP_SECRET: '${PUSHER_APP_SECRET}'
        ports:
            - '${PUSHER_PORT:-6001}:6001'
            - '${PUSHER_METRICS_PORT:-9601}:9601'
        networks:
            - webapp



